name: PR Check

on:
  pull_request:
    branches: [main]

jobs:
  pr-check:
    name: PR Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint:check

      - name: Run format check
        run: npm run format:check

      - name: Build
        run: npm run build

      - name: Run security audit
        run: npm audit --audit-level=high
        continue-on-error: true

      # Dry run semantic-release to validate the next version
      - name: Semantic Release (Dry Run)
        uses: cycjimmy/semantic-release-action@v5
        with:
          semantic_version: 24
          dry_run: true
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
