name: CI/CD

permissions: # Add default permissions, release job will override if needed
  contents: read

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]

jobs:
  test:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint:check

      - name: Run format check
        run: npm run format:check

      - name: Build
        run: npm run build

  security:
    name: Security Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed for checkout and CodeQL
      security-events: write # Needed for CodeQL alert uploads
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level=high
        continue-on-error: true # Allow workflow to continue even if npm audit finds vulnerabilities

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [test, security] # Run after test and security checks pass
    # Run only on pushes to main, not on tags (semantic-release creates tags)
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write # Allow tagging, committing package.json/changelog
      issues: write # Allow commenting on issues/PRs
      pull-requests: write # Allow commenting on issues/PRs
      id-token: write # Needed for provenance publishing to npm
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
